services:
  react_native:
    container_name: Frontend-React
    build: frontend
    ports:
      - 19000:19000
    volumes:
      - ./frontend:/home/app/frontend
      - ./frontend/node_modules:/home/app/frontend/node_modules
  nest:
    container_name: Backend-Nest
    image: node:16-alpine
    working_dir: /home/app/backend
    command: yarn start:dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/home/app/backend
      - ./backend/node_modules:/home/app/backend/node_modules
  mongo_db:
    container_name: Mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rainbow
      - MONGO_INITDB_ROOT_PASSWORD=unicorn
    image: mongo:4.2.0
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
  mongo_express:
    container_name: Mongo-Express
    image: mongo-express
    depends_on:
      - mongo_db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rainbow
      - ME_CONFIG_MONGODB_ADMINPASSWORD=unicorn
      - ME_CONFIG_MONGODB_SERVER=mongo_db
volumes:
  db-data:
