services:
  react_native:
    container_name: Frontend-React
    restart: always
    image: paer12/tunetonic-frontend
    ports:
      - 3000:3000
  nest:
    container_name: Backend-Nest
    restart: always
    image: paer12/tunetonic-backend-dev
    ports:
      - 8080:8080
  mongo_db:
    container_name: Mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rainbow
      - MONGO_INITDB_ROOT_PASSWORD=unicorn
    image: mongo:4.2.0
    ports:
      - 27017:27017
