services:
  mongo:
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rainbow
      - MONGO_INITDB_ROOT_PASSWORD=unicorn
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    # networks:
    #   - nest-mongo
    ports:
      - 27017:27017
# networks:
#   react-nest:
#   nest-mongo:
