name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  Deployment-pipe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.fdmci.hva.nl/aldabap/tunetonic"
        env:
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.fdmci.hva.nl"
          GITLAB_USERNAME: "aldabap"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "30017"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
