name: Nest CI

on:
  push:
    paths:
      - '.github/workflows/nest-ci.yml'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  CI-CD-Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn

      - name: Test linting
        run: yarn lint

      - name: Test application
        run: yarn test

      - name: Snyk monitor
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
