name: React CI

on:
  push:
    paths:
      - ".github/workflows/react-ci.yml"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  CI-CD-Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn

      # - name: Test application
      #   run: yarn test
# test pipeline